import { studio, variants, getVariant } from '../data/studio.js';
import { variantConfigs } from '../variants/config.js';

const $ = (selector, root = document) => root.querySelector(selector);
const esc = (value = '') => String(value).replace(/[&<>\"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', "'":'&#39;' }[char]));
const params = new URLSearchParams(location.search);
let activeVariant = getVariant(params.get('v') || localStorage.getItem('northstar-variant') || 'v1');
function currentConfig() { return variantConfigs[activeVariant] || variantConfigs.v1; }
function setUrl() { history.replaceState(null, '', `${location.pathname}?v=${activeVariant}`); }
function renderHeader() {
  $('#headerMount').innerHTML = `<div class="header-inner"><a class="wordmark" href="#home" aria-label="Northstar Ink home"><span class="mark">✳</span><span>NORTHSTAR<br><small>INK / NYC</small></span></a><nav class="main-nav" aria-label="Main navigation"><a href="#work">Work</a><a href="#artists">Artists</a><a href="#process">Process</a><a href="#studio">Studio</a><details class="home-menu"><summary>Home <span>＋</span></summary><div class="variant-menu">${Object.entries(variants).map(([id, item]) => `<button data-variant="${id}" class="${id === activeVariant ? 'active' : ''}"><b>${id.toUpperCase()}</b><span>${esc(item.label)}</span></button>`).join('')}</div></details></nav><a class="header-cta" href="#book">Book a session <span>↗</span></a><button class="mobile-toggle" aria-label="Open menu">Menu</button></div>`;
  document.querySelectorAll('[data-variant]').forEach((button) => button.addEventListener('click', () => { activeVariant = getVariant(button.dataset.variant); localStorage.setItem('northstar-variant', activeVariant); setUrl(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }));
}
function hero() { const c=currentConfig(); return `<section class="hero" id="home"><div class="hero-grid"><div class="hero-meta"><span>${esc(c.heroKicker)}</span><span>Bookings open / 2026</span></div><div class="hero-copy"><p class="eyebrow">Northstar Ink — ${esc(c.heroLabel)}</p><h1>${esc(c.heroTitle).replace('\\n','<br>')}</h1><p class="hero-text">${esc(c.heroText)}</p><div class="hero-actions"><a class="button button-fill" href="#book">${esc(c.cta)} <span>↗</span></a><a class="text-link" href="#work">See selected work <span>↓</span></a></div></div><figure class="hero-visual"><img src="${c.heroImage}" alt="Tattoo artist at work in the studio"><figcaption><span>01 / 05</span><span>Scroll to explore</span></figcaption></figure></div></section>`; }
function intro() { return `<section class="intro section-pad"><div class="section-label">/ 01 — The idea</div><div class="intro-copy"><p class="display">${esc(currentConfig().intro)}</p><p class="body-copy">Northstar is a tattoo studio and visual arts practice for people who want more than a mark. Our artists work across fine line, blackwork, realism, ornamental, and custom composition — always with care for the story underneath.</p></div></section>`; }
function work() { return `<section class="work section-pad" id="work"><div class="section-head"><div><div class="section-label">/ 02 — Selected work</div><h2>Made to be<br><em>kept.</em></h2></div><p>Healed work only.<br>Custom and flash.</p></div><div class="work-grid">${studio.work.slice(0,6).map((item,i)=>`<a class="work-card work-${i+1}" href="#book"><div class="image-wrap"><img src="${item.image}" alt="${esc(item.title)} tattoo work"><span class="card-index">0${i+1}</span></div><div class="card-meta"><span>${esc(item.title)}</span><span>${esc(item.meta)}</span></div></a>`).join('')}</div><a class="button button-outline more-link" href="#book">View the full archive <span>↗</span></a></section>`; }
function artists() { return `<section class="artists section-dark section-pad" id="artists"><div class="section-head"><div><div class="section-label">/ 03 — The residents</div><h2>Find your<br><em>artist.</em></h2></div><p>Different hands.<br>One shared standard.</p></div><div class="artist-grid">${studio.artists.map((artist,i)=>`<article class="artist-card"><div class="artist-photo"><img src="${artist.image}" alt="${esc(artist.name)} tattoo artist"><span>0${i+1}</span></div><div class="artist-info"><h3>${esc(artist.name)}</h3><p>${esc(artist.role)}</p><a href="#book">Book with ${esc(artist.name.split(' ')[0])} ↗</a></div></article>`).join('')}</div></section>`; }
function process() { const steps=[['01','Consult','Placement, size, references, budget. Twenty minutes with your artist.','free'],['02','Stencil','A clear design direction you can approve on skin before any needle.','on skin first'],['03','Ink','A calm, considered session with time for every line to land correctly.','by session'],['04','Heal','Aftercare is part of the work. Leave with a guide and a check-in.','4 weeks']]; return `<section class="process section-pad" id="process"><div class="section-label">/ 04 — How it runs</div><div class="process-layout"><h2>From idea<br>to <em>ink.</em></h2><div class="process-list">${steps.map(s=>`<article><span class="step-no">${s[0]}</span><div><h3>${s[1]}</h3><p>${s[2]}</p></div><b>${s[3]}</b></article>`).join('')}</div></div></section>`; }
function studioSection() { return `<section class="studio section-dark" id="studio"><div class="studio-photo"><img src="assets/tattoo-process.jpg" alt="Tattoo artist working with a client"><div class="photo-note">A working studio<br>for living art.</div></div><div class="studio-copy section-pad"><div class="section-label">/ 05 — The studio</div><h2>More than<br>a <em>tattoo.</em></h2><p>${esc(studio.about)}</p><div class="details"><div><span>Find us</span><strong>${esc(studio.location)}</strong></div><div><span>Open</span><strong>${esc(studio.hours)}</strong></div></div><a class="button button-outline" href="#book">Come say hello <span>↗</span></a></div></section>`; }
function faq() { return `<section class="faq section-pad"><div class="section-label">/ 06 — Good to know</div><div class="faq-layout"><h2>Questions,<br><em>answered.</em></h2><div>${studio.faq.map((item,i)=>`<details ${i===0?'open':''}><summary><span>0${i+1}</span>${esc(item[0])}<b>＋</b></summary><p>${esc(item[1])}</p></details>`).join('')}</div></div></section>`; }
function book() { return `<section class="book section-pad" id="book"><div class="book-copy"><div class="section-label">/ 07 — Book in</div><h2>Ready when<br><em>you are.</em></h2><p>Tell us a little about what you are thinking. We’ll match you with the right artist and get back to you within 48 hours.</p><div class="contact-lines"><span>${esc(studio.email)}</span><span>${esc(studio.phone)}</span></div></div><form class="booking-form"><label>Name<input required name="name" placeholder="Your name"></label><label>Email<input required type="email" name="email" placeholder="you@example.com"></label><label>Preferred artist<input name="artist" placeholder="Anyone / not sure yet"></label><label>Your idea<textarea required name="idea" placeholder="Placement, size, style, reference links..."></textarea></label><button class="button button-fill" type="submit">Send enquiry <span>↗</span></button><p class="form-message" role="status"></p></form></section>`; }
function footer() { $('#footerMount').innerHTML=`<div class="footer-top"><a class="wordmark" href="#home"><span class="mark">✳</span><span>NORTHSTAR<br><small>INK / NYC</small></span></a><p>Custom tattooing, visual arts,<br>and a good reason to come back.</p><a href="#home">Back to top ↑</a></div><div class="footer-bottom"><span>© 2026 Northstar Ink</span><span>New York, NY</span><div><a href="#studio">Instagram</a><a href="#studio">Aftercare</a><a href="#studio">Policies</a></div></div>`; }
function render() { document.body.dataset.variant=activeVariant; renderHeader(); $('#app').innerHTML=hero()+intro()+work()+artists()+process()+studioSection()+faq()+book(); footer(); attach(); }
function attach() { const form=$('.booking-form'); form?.addEventListener('submit',(e)=>{e.preventDefault(); $('.form-message').textContent='Thank you — your note is in. We’ll be in touch within 48 hours.'; form.reset();}); const toggle=$('.mobile-toggle'); toggle?.addEventListener('click',()=>document.body.classList.toggle('nav-open')); }
render();
